CREATE DATABASE moviedb;
USE moviedb;
CREATE TABLE movies (id varchar(10)not null DEFAULT '', title varchar(100) not null DEFAULT '', year integer not null, director varchar(100) not null DEFAULT '', PRIMARY KEY (id));
CREATE TABLE stars (id varchar(10)not null DEFAULT '', name varchar(100) not null DEFAULT '', birthYear integer, PRIMARY KEY (id));
CREATE TABLE stars_in_movies (starId varchar(10) not null DEFAULT '', movieId varchar(10) not null DEFAULT '', FOREIGN KEY (starId) REFERENCES stars(id), FOREIGN KEY (movieId) REFERENCES movies(id));
CREATE TABLE genres (id integer AUTO_INCREMENT not null, name varchar(32) DEFAULT '', PRIMARY KEY (id));
CREATE TABLE genres_in_movies (genreId integer not null , movieId varchar(10) not null DEFAULT '', FOREIGN KEY (genreId) REFERENCES genres(id), FOREIGN KEY (movieId) REFERENCES movies(id));
CREATE TABLE creditcards (id varchar(20) not null DEFAULT '', firstName varchar(50) not null DEFAULT '', lastName varchar(50) not null DEFAULT '', expiration date not null, PRIMARY KEY (id));
CREATE TABLE customers (id integer AUTO_INCREMENT not null, firstName varchar(50) not null DEFAULT '', lastName varchar(50) not null DEFAULT '', ccId varchar(20) not null DEFAULT '', address varchar(200) not null DEFAULT '', email varchar(50) not null DEFAULT '', password varchar(20) not null DEFAULT '', FOREIGN KEY (ccId) REFERENCES creditcards(id), PRIMARY KEY (id));
CREATE TABLE sales (id integer AUTO_INCREMENT not null, customerId integer not null, movieId varchar(10) not null DEFAULT '', saleDate date not null, FOREIGN KEY (customerId) REFERENCES customers(id), FOREIGN KEY (movieId) REFERENCES movies(id), PRIMARY KEY (id));
CREATE TABLE ratings (movieId varchar(10) not null DEFAULT '', rating float not null, numVotes integer not null, FOREIGN KEY (movieId) REFERENCES movies(id));
